package IClinicServiceCorba;


/**
* IClinicServiceCorba/DSMSCorbaHelper.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IClinicServiceCorba.idl
* Wednesday, June 22, 2016 5:13:48 PM EDT
*/

abstract public class DSMSCorbaHelper
{
  private static String  _id = "IDL:IClinicServiceCorba/DSMSCorba:1.0";

  public static void insert (org.omg.CORBA.Any a, IClinicServiceCorba.DSMSCorba that)
  {
    org.omg.CORBA.portable.OutputStream out = a.create_output_stream ();
    a.type (type ());
    write (out, that);
    a.read_value (out.create_input_stream (), type ());
  }

  public static IClinicServiceCorba.DSMSCorba extract (org.omg.CORBA.Any a)
  {
    return read (a.create_input_stream ());
  }

  private static org.omg.CORBA.TypeCode __typeCode = null;
  synchronized public static org.omg.CORBA.TypeCode type ()
  {
    if (__typeCode == null)
    {
      __typeCode = org.omg.CORBA.ORB.init ().create_interface_tc (IClinicServiceCorba.DSMSCorbaHelper.id (), "DSMSCorba");
    }
    return __typeCode;
  }

  public static String id ()
  {
    return _id;
  }

  public static IClinicServiceCorba.DSMSCorba read (org.omg.CORBA.portable.InputStream istream)
  {
    return narrow (istream.read_Object (_DSMSCorbaStub.class));
  }

  public static void write (org.omg.CORBA.portable.OutputStream ostream, IClinicServiceCorba.DSMSCorba value)
  {
    ostream.write_Object ((org.omg.CORBA.Object) value);
  }

  public static IClinicServiceCorba.DSMSCorba narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof IClinicServiceCorba.DSMSCorba)
      return (IClinicServiceCorba.DSMSCorba)obj;
    else if (!obj._is_a (id ()))
      throw new org.omg.CORBA.BAD_PARAM ();
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      IClinicServiceCorba._DSMSCorbaStub stub = new IClinicServiceCorba._DSMSCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

  public static IClinicServiceCorba.DSMSCorba unchecked_narrow (org.omg.CORBA.Object obj)
  {
    if (obj == null)
      return null;
    else if (obj instanceof IClinicServiceCorba.DSMSCorba)
      return (IClinicServiceCorba.DSMSCorba)obj;
    else
    {
      org.omg.CORBA.portable.Delegate delegate = ((org.omg.CORBA.portable.ObjectImpl)obj)._get_delegate ();
      IClinicServiceCorba._DSMSCorbaStub stub = new IClinicServiceCorba._DSMSCorbaStub ();
      stub._set_delegate(delegate);
      return stub;
    }
  }

}
