package IClinicServiceCorba;


/**
* IClinicServiceCorba/DSMSCorba.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IClinicServiceCorba.idl
* Wednesday, June 22, 2016 5:13:48 PM EDT
*/

public interface DSMSCorba extends DSMSCorbaOperations, org.omg.CORBA.Object, org.omg.CORBA.portable.IDLEntity 
{
} // interface DSMSCorba
