package IClinicServiceCorba;


/**
* IClinicServiceCorba/DSMSCorbaPOA.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IClinicServiceCorba.idl
* Wednesday, June 22, 2016 5:13:48 PM EDT
*/

public abstract class DSMSCorbaPOA extends org.omg.PortableServer.Servant
 implements IClinicServiceCorba.DSMSCorbaOperations, org.omg.CORBA.portable.InvokeHandler
{

  // Constructors

  private static java.util.Hashtable _methods = new java.util.Hashtable ();
  static
  {
    _methods.put ("createDoctorRecord", new java.lang.Integer (0));
    _methods.put ("createNurseRecord", new java.lang.Integer (1));
    _methods.put ("editRecord", new java.lang.Integer (2));
    _methods.put ("transferRecord", new java.lang.Integer (3));
    _methods.put ("deleteRecord", new java.lang.Integer (4));
    _methods.put ("getRecord", new java.lang.Integer (5));
  }

  public org.omg.CORBA.portable.OutputStream _invoke (String $method,
                                org.omg.CORBA.portable.InputStream in,
                                org.omg.CORBA.portable.ResponseHandler $rh)
  {
    org.omg.CORBA.portable.OutputStream out = null;
    java.lang.Integer __method = (java.lang.Integer)_methods.get ($method);
    if (__method == null)
      throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);

    switch (__method.intValue ())
    {
       case 0:  // IClinicServiceCorba/DSMSCorba/createDoctorRecord
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String address = in.read_string ();
         String phone = in.read_string ();
         String specialization = in.read_string ();
         String location = in.read_string ();
         String managerID = in.read_string ();
         this.createDoctorRecord (firstName, lastName, address, phone, specialization, location, managerID);
         out = $rh.createReply();
         break;
       }

       case 1:  // IClinicServiceCorba/DSMSCorba/createNurseRecord
       {
         String firstName = in.read_string ();
         String lastName = in.read_string ();
         String designation = in.read_string ();
         String status = in.read_string ();
         String date = in.read_string ();
         String location = in.read_string ();
         String managerID = in.read_string ();
         this.createNurseRecord (firstName, lastName, designation, status, date, location, managerID);
         out = $rh.createReply();
         break;
       }

       case 2:  // IClinicServiceCorba/DSMSCorba/editRecord
       {
         String recordID = in.read_string ();
         String fieldName = in.read_string ();
         String fieldValue = in.read_string ();
         this.editRecord (recordID, fieldName, fieldValue);
         out = $rh.createReply();
         break;
       }

       case 3:  // IClinicServiceCorba/DSMSCorba/transferRecord
       {
         String managerID = in.read_string ();
         String recordID = in.read_string ();
         String remoteClinicServerName = in.read_string ();
         this.transferRecord (managerID, recordID, remoteClinicServerName);
         out = $rh.createReply();
         break;
       }

       case 4:  // IClinicServiceCorba/DSMSCorba/deleteRecord
       {
         String recordID = in.read_string ();
         this.deleteRecord (recordID);
         out = $rh.createReply();
         break;
       }

       case 5:  // IClinicServiceCorba/DSMSCorba/getRecord
       {
         String $result = null;
         $result = this.getRecord ();
         out = $rh.createReply();
         out.write_string ($result);
         break;
       }

       default:
         throw new org.omg.CORBA.BAD_OPERATION (0, org.omg.CORBA.CompletionStatus.COMPLETED_MAYBE);
    }

    return out;
  } // _invoke

  // Type-specific CORBA::Object operations
  private static String[] __ids = {
    "IDL:IClinicServiceCorba/DSMSCorba:1.0"};

  public String[] _all_interfaces (org.omg.PortableServer.POA poa, byte[] objectId)
  {
    return (String[])__ids.clone ();
  }

  public DSMSCorba _this() 
  {
    return DSMSCorbaHelper.narrow(
    super._this_object());
  }

  public DSMSCorba _this(org.omg.CORBA.ORB orb) 
  {
    return DSMSCorbaHelper.narrow(
    super._this_object(orb));
  }


} // class DSMSCorbaPOA
