package IClinicServiceCorba;

/**
* IClinicServiceCorba/DSMSCorbaHolder.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IClinicServiceCorba.idl
* Wednesday, June 22, 2016 5:13:48 PM EDT
*/

public final class DSMSCorbaHolder implements org.omg.CORBA.portable.Streamable
{
  public IClinicServiceCorba.DSMSCorba value = null;

  public DSMSCorbaHolder ()
  {
  }

  public DSMSCorbaHolder (IClinicServiceCorba.DSMSCorba initialValue)
  {
    value = initialValue;
  }

  public void _read (org.omg.CORBA.portable.InputStream i)
  {
    value = IClinicServiceCorba.DSMSCorbaHelper.read (i);
  }

  public void _write (org.omg.CORBA.portable.OutputStream o)
  {
    IClinicServiceCorba.DSMSCorbaHelper.write (o, value);
  }

  public org.omg.CORBA.TypeCode _type ()
  {
    return IClinicServiceCorba.DSMSCorbaHelper.type ();
  }

}
