package IClinicServiceCorba;


/**
* IClinicServiceCorba/DSMSCorbaOperations.java .
* Generated by the IDL-to-Java compiler (portable), version "3.2"
* from IClinicServiceCorba.idl
* Wednesday, June 22, 2016 5:13:48 PM EDT
*/

public interface DSMSCorbaOperations 
{
  void createDoctorRecord (String firstName, String lastName, String address, String phone, String specialization, String location, String managerID);
  void createNurseRecord (String firstName, String lastName, String designation, String status, String date, String location, String managerID);
  void editRecord (String recordID, String fieldName, String fieldValue);
  void transferRecord (String managerID, String recordID, String remoteClinicServerName);
  void deleteRecord (String recordID);
  String getRecord ();
} // interface DSMSCorbaOperations
